dubbo:
  application:
    name: mio
  registry:
    address: zookeeper://10.1.0.64:2181
    timeout: 6000

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
#开启sql日志
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

example:
  service:
    prefix: ======
    suffix: 111111

    enable: true

server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.1.1.176:3306/fresh_news?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: d_dev_rw
    password: Ymn2738#HwqBAo
    name: jhcgjSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
